name: Pull request

on: pull_request

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: 📖 Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: ⚙️ Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 10

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🕵️‍♂️ Verify lint
        run: pnpm lint

      - name: 🕵️‍♂️ Verify test
        run: pnpm test

      - name: 🕵️‍♂️ Verify build
        run: pnpm build
